title: "Eric J. Mei"
email: "emei@uw.edu"
description: "Research Page for EJM"
baseurl: ""
url: "https://ericjmei.github.io"
author:
  name: "Eric J. Mei"
  email: "emei@uw.edu"
  avatar: "Headshot.jpg"
  googlescholar: "https://scholar.google.com/citations?user=y8gpQDoAAAAJ&hl=en"
  github: "ericjmei"
  linkedin: "eric-mei-595287173"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
